[ERROR] 2018-01-11 22:28:39,250 | /home/digitalprizm/workspace/FrappeProject/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2018-01-11 22:28:39.002680-127.0.0.1-434
